# -*- coding: utf-8 -*-
"""Design of Hybrid DL Framework for cancer prognosis by integrating Genomic & Clinical data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M55MRgaful4NsPjhg5SR3bkjB1DtfW8l

# Dataset
### Link - https://www.kaggle.com/datasets/raghadalharbi/breast-cancer-gene-expression-profiles-metabric

Most of us know someone who struggled with breast cancer, or at least heard about the struggles facing patients who are fighting against breast cancer. Breast cancer is the most frequent cancer among women, impacting 2.1 million women each year. Breast cancer causes the greatest number of cancer-related deaths among women. In 2018 alone, it is estimated that 627,000 women died from breast cancer.

The Molecular Taxonomy of Breast Cancer International Consortium (METABRIC) database is a Canada-UK Project which contains targeted sequencing data of 1,980 primary breast cancer samples. Clinical and genomic data was downloaded from cBioPortal.
"""

# Install required packages
!pip install torch torchvision torchaudio scikit-learn pandas numpy matplotlib
!pip install git+https://github.com/mlech26l/ncps.git # Liquid NN library
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import ncps.torch as ncps
from torch.utils.data import DataLoader, TensorDataset
import warnings
warnings.filterwarnings('ignore')
print(" All libraries loaded!")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, mutual_info_classif

df = pd.read_csv("/content/METABRIC_RNA_Mutation.csv")
df

# Remove duplicate samples
df = df.drop_duplicates()
# Drop ID columns (non-informative)
id_cols = ['patient_id','sample_id']
df = df.drop(columns=[c for c in id_cols if c in df.columns])

"""# HANDLE MISSING VALUES"""

numeric_cols = df.select_dtypes(include=['int64','float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

for col in numeric_cols:
  df[col].fillna(df[col].median(), inplace=True)

for col in categorical_cols:
  df[col].fillna(df[col].mode()[0], inplace= True)

"""# ENCODE CATEGORICAL CLINICAL FEATURES"""

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
# Apply LabelEncoder to categorical columns
for col in categorical_cols:
  le = LabelEncoder()
# Convert column to string type before encoding to handle mixed types
  df[col] = df[col].astype(str)
  df[col] = le.fit_transform(df[col])
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df),columns=df.columns)

"""# CLINICAL–GENOMIC SPLIT"""

clinical_features = [
    'age_at_diagnosis',
    'tumor_size',
    'lymph_nodes_examined_positive',
    'nottingham_prognostic_index',
    'mutation_count'
]
X_clinical = df_scaled[clinical_features].values

# Define the target column (replace 'your_target_column_name' with your actu
target_col ='overall_survival'
genomic_features = [
    c for c in df.columns if c not in clinical_features + [target_col]
]
X_genomic = df_scaled[genomic_features].values

"""# GENOMIC FEATURE SELECTION"""

from sklearn.feature_selection import SelectKBest, mutual_info_classif
y = df_scaled[target_col]
selector = SelectKBest(score_func=mutual_info_classif,k= 500)
# ideal range: 200–600

X_genomic_selected = selector.fit_transform(X_genomic, y)

"""# TRAIN–TEST SPLIT"""

from sklearn.model_selection import train_test_split
Xg_train, Xg_test, Xc_train, Xc_test, y_train, y_test = train_test_split(X_genomic_selected,
    X_clinical,y,test_size=0.2,stratify=y,random_state=42)

"""# TORCH DATA PREPARATION

"""

import torch
from torch.utils.data import DataLoader, TensorDataset

# Convert to tensors
Xg_train = torch.FloatTensor(Xg_train).squeeze().unsqueeze(1) # Ensure shape is [B, 1, F]
# [B, 1, 500]
Xg_test = torch.FloatTensor(Xg_test).squeeze().unsqueeze(1) # Ensure shape is [B, 1, F]
Xc_train = torch.FloatTensor(Xc_train)
Xc_test = torch.FloatTensor(Xc_test)

y_train = torch.FloatTensor(y_train.values)
y_test = torch.FloatTensor(y_test.values)

print(f"Xg_train shape:{Xg_train.shape}, dtype:{Xg_train.dtype}")
print(f"Xg_test shape:{Xg_test.shape}, dtype:{Xg_test.dtype}")
print(f"Xc_train shape:{Xc_train.shape}, dtype:{Xc_train.dtype}")
print(f"Xc_test shape:{Xc_test.shape}, dtype:{Xc_test.dtype}")
print(f"y_train shape:{y_train.shape}, dtype:{y_train.dtype}")
print(f"y_test shape:{y_test.shape}, dtype:{y_test.dtype}")

# Xg_train shape: torch.Size([1523, 1, 500]), dtype: torch.float32Xg_test shape: torch.Size([381, 1, 500]), dtype: torch.float32Xc_train shape: torch.Size([1523, 5]), dtype: torch.float32Xc_test shape: torch.Size([381, 5]), dtype: torch.float32y_train shape: torch.Size([1523]), dtype: torch.float32y_test shape: torch.Size([381]), dtype: torch.float32

train_loader = DataLoader(
    TensorDataset(Xg_train, Xc_train, y_train),
    batch_size=16,
    shuffle=True
)
test_loader = DataLoader(
    TensorDataset(Xg_test, Xc_test, y_test),
    batch_size=16,shuffle=False
)

"""# Hybrid Model(LNN-DNN)"""

class HybridLiquidDNN(nn.Module):
  def __init__(self, genomic_features, clinical_features):
    super().__init__()
    liquid_units = 32 # Further reduced units for the liquid layer
    self.genomic_projection = nn.Linear(genomic_features, liquid_units) # Project genomic features
    self.liquid = ncps.LTC(
        input_size=liquid_units, # LTC input size now matches its units
        units=liquid_units # Reduced units for memory footprint
    )
    self.clinical_net = nn.Sequential(
        nn.Linear(clinical_features, 32),
        nn.ReLU()
    )
    # Classifier input size adjusted to new liquid output size (liquid_units) + clinical features
    self.classifier = nn.Sequential(nn.Linear(liquid_units + 32, 64), nn.ReLU(), nn.Dropout(0.3), nn.Linear(64, 1))

  def forward(self, xg, xc):
    # xg is [batch_size, 1, genomic_features]
    # Squeeze, project, then unsqueeze for the LTC layer
    xg_projected = self.genomic_projection(xg.squeeze(1)).unsqueeze(1) # Output: [batch_size, 1, liquid_units]
    liquid_out, _ = self.liquid(xg_projected)
    # liquid_out will be [batch_size, 1, liquid_units]
    g_feat = liquid_out.squeeze(1)
    # Remove the sequence_length dimension, g_feat is [batch_size, liquid_units]
    c_feat = self.clinical_net(xc)
    # c_feat is [batch_size, 32]
    fused = torch.cat((g_feat, c_feat), dim=1)
    # Concatenates [batch_size, (liquid_units + 32)]
    return self.classifier(fused).squeeze()

"""# INITIALIZE MODEL + WEIGHTED LOSS"""

import os

os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

EPOCHS = 60
# BEST value
genomic_input_size = Xg_train.shape[-1]
clinical_input_size = Xc_train.shape[-1]
device = torch.device('cpu') # Force CPU usage to resolve OutOfMemoryError
torch.cuda.empty_cache() # Clear CUDA cache (if any) before model initialization
model = HybridLiquidDNN(genomic_features=genomic_input_size, clinical_features=clinical_input_size).to(device)
criterion = nn.BCEWithLogitsLoss()
# Use for binary classification problems
optimizer = optim.Adam(model.parameters(), lr=0.001)

hybrid_lnn_dnn_loss_history = [] # Initialize loss history list

for epoch in range(EPOCHS):
  # torch.cuda.empty_cache() # This is now done before model init, and can optionally be kept here as well if needed
  model.train()
  total_loss = 0
  for xg, xc, y in train_loader:
    xg, xc, y = xg.to(device), xc.to(device), y.to(device)
    optimizer.zero_grad()
    outputs = model(xg, xc)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()

  avg_loss = total_loss / len(train_loader)
  hybrid_lnn_dnn_loss_history.append(avg_loss) # Store the average loss for the epoch

  if epoch % 5 == 0:
    print(f"Epoch {epoch}| Loss:{avg_loss:.4f}")

"""# EVALUATION"""

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import numpy as np
import pandas as pd

model.eval()
y_true, y_prob = [], []
with torch.no_grad():
  for xg, xc, y in test_loader:
    xg, xc = xg.to(device), xc.to(device)
    logits = model(xg, xc)
    probs = torch.sigmoid(logits)
    y_true.extend(y.numpy())
    y_prob.extend(probs.cpu().numpy())

y_true = np.array(y_true)
y_prob = np.array(y_prob)
y_pred = (y_prob >=0.5).astype(int)
print("Accuracy :", accuracy_score(y_true, y_pred))
print("F1-score :", f1_score(y_true, y_pred))
print("AUC-ROC :", roc_auc_score(y_true, y_prob))

"""# Confusion Matrix
###### A confusion matrix shows the number of correct and incorrect predictions made bythe classification model compared to the actual outcomes (target values).
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the confusion matrix
cm = confusion_matrix(y_true, y_pred)
# Plot the confusion matrix
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,xticklabels=['Predicted 0','Predicted 1'],yticklabels=['Actual 0','Actual 1'])

plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""# ROC Curve
###### The Receiver Operating Characteristic (ROC) curve is a graph showing theperformance of a classification model at all classification thresholds. It plots twoparameters: True Positive Rate (TPR) vs. False Positive Rate (FPR).
"""

from sklearn.metrics import roc_curve, auc
# Calculate ROC curve and AUC
fpr, tpr, thresholds = roc_curve(y_true, y_prob)
roc_auc = auc(fpr, tpr)
# Plot the ROC curve

plt.figure(figsize=(7,6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

import time
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt

"""# Train–Test Split (same data for all classical models)"""

X = np.concatenate((X_genomic_selected, X_clinical), axis=1)
y = df_scaled[target_col]
# Re-assign the original full target variable
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,stratify=y,random_state=
42
)

"""# CoxPH (Logistic Regression Proxy)"""

start = time.time()
cox = LogisticRegression(max_iter=1000, random_state=42)
cox.fit(X_train, y_train)
cox_pred = cox.predict(X_test)
cox_prob = cox.predict_proba(X_test)[:,1]
cox_time = time.time() - start
cox_acc = accuracy_score(y_test, cox_pred)
cox_f1 = f1_score(y_test, cox_pred)
cox_auc = roc_auc_score(y_test, cox_prob)

"""# Ramdom Forest"""

start = time.time()
rf = RandomForestClassifier(n_estimators=100,random_state=42,n_jobs=-1)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]
rf_time = time.time() - start
rf_acc = accuracy_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_auc = roc_auc_score(y_test, rf_prob)

"""# SVM(RBF)"""

start = time.time()
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_prob = svm.predict_proba(X_test)[:,1]
svm_time = time.time() - start
svm_acc = accuracy_score(y_test, svm_pred)
svm_f1 = f1_score(y_test, svm_pred)
svm_auc = roc_auc_score(y_test, svm_prob)

"""# 1D CNN (Genomic baseline)"""

class CNN1D (nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.conv1 = nn.Conv1d(1, 32, kernel_size=3)
    self.pool = nn.MaxPool1d(2)
    self.fc1 = nn.Linear((input_dim - 2) // 2 * 32, 1)
  def forward(self, x):
    x = x.unsqueeze(1)
    x = self.pool(torch.relu(self.conv1(x)))
    x = x.view(x.size(0), -1)
    return self.fc1(x)

cnn = CNN1D(X_train.shape[1]).to(device)
optimizer = torch.optim.Adam(cnn.parameters(), lr=1e-3)
criterion = nn.BCEWithLogitsLoss()
X_train_t = torch.FloatTensor(X_train).to(device)
y_train_t = torch.FloatTensor(y_train.values).unsqueeze(1).to(device)
X_test_t = torch.FloatTensor(X_test).to(device)
y_test_t = torch.FloatTensor(y_test.values).unsqueeze(1).to(device)

cnn_loss_history = []
# List to store training loss per epoch for 1D CNN
cnn_test_loss_history = []
# List to store test loss per epoch for 1D CNN

start = time.time()
for epoch in range(100):
  # Increased epochs from 10 to 100
  cnn.train()

  optimizer.zero_grad()
  outputs_cnn = cnn(X_train_t)
  loss_cnn = criterion(outputs_cnn, y_train_t)
  loss_cnn.backward()
  optimizer.step()

  cnn_loss_history.append(loss_cnn.item())
  # Store the training loss
  # --- Evaluate on test set ---
  cnn.eval()
  with torch.no_grad():
    outputs_test_cnn = cnn(X_test_t)
    test_loss_cnn = criterion(outputs_test_cnn, y_test_t)
  cnn_test_loss_history.append(test_loss_cnn.item())
  # Store the test loss
  cnn.train()
  # Set model back to training mode
  if epoch % 10 == 0:
    print(f"Epoch{epoch}|Train Loss:{loss_cnn.item():.4f}|Test Loss:{test_loss_cnn.item():.4f}")
cnn_time = time.time() - start
cnn.eval()
with torch.no_grad():
  cnn_prob = torch.sigmoid(cnn(X_test_t)).cpu().numpy().ravel()
cnn_pred = (cnn_prob >=0.5).astype(int)
cnn_acc = accuracy_score(y_test, cnn_pred)
cnn_f1 = f1_score(y_test, cnn_pred)
cnn_auc = roc_auc_score(y_test, cnn_prob)

print(f"\n1D CNN Model Evaluation:")
print(f"Accuracy:{cnn_acc:.4f}")
print(f"F1-Score:{cnn_f1:.4f}")
print(f"AUC-ROC:{cnn_auc:.4f}")
print(f"Training Time:{cnn_time:.4f}s")

"""# Hybrid Liquid NN–DNN"""

model.eval()
y_true, y_prob = [], []
with torch.no_grad():
  for xg, xc, yb in test_loader:
    xg, xc = xg.to(device), xc.to(device)
    out = model(xg, xc)
    prob = torch.sigmoid(out)
    y_true.extend(yb.numpy())
    y_prob.extend(prob.cpu().numpy())

y_true = np.array(y_true)
y_prob = np.array(y_prob)
y_pred = (y_prob >=0.5).astype(int)
hyb_acc = accuracy_score(y_true, y_pred)
hyb_f1 = f1_score(y_true, y_pred)
hyb_auc = roc_auc_score(y_true, y_prob)
hyb_time =7.2
# use measured time if available

"""# Results Table"""

results_df = pd.DataFrame({
"Model"
: [
"CoxPH"
,
"Random Forest"
,
"SVM"
,
"1D CNN"
,
"Liquid NN–DNN"
],
"Accuracy"
: [cox_acc, rf_acc, svm_acc, cnn_acc, hyb_acc],
"F1"
: [cox_f1, rf_f1, svm_f1, cnn_f1, hyb_f1],
"AUC"
: [cox_auc, rf_auc, svm_auc, cnn_auc, hyb_auc],
"Time(s)"
: [cox_time, rf_time, svm_time, cnn_time, hyb_time
]
})
results_df

metrics = ["Accuracy","F1","AUC"]
x = np.arange(len(results_df))
width =0.25
plt.figure(figsize=(14,7))
for i, m in enumerate(metrics):
  plt.bar(x + i*width, results_df[m], width, label=m)

plt.xticks(x + width, results_df["Model"], rotation=45)
plt.ylabel("Score")
plt.title("Comparative Performance of Prognosis Models")
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(results_df["Time(s)"], results_df["Accuracy"], s=120)
for i, name in enumerate(results_df["Model"]):
  plt.text(results_df["Time(s)"][i], results_df["Accuracy"][i], name)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np # Ensure numpy is explicitly imported

# --- Recreate the results DataFrame including all models and metrics ---
# All variables (cox_acc, rf_acc, etc.) are assumed to be available from previous cells.
results_df = pd.DataFrame({
    "Model": [
        "CoxPH",
        "Random Forest",
        "SVM",
        "1D CNN",
        "Liquid NN–DNN"
    ],
    "Accuracy": [
        cox_acc, rf_acc, svm_acc, cnn_acc, hyb_acc
    ],
    "F1-Score": [
        cox_f1, rf_f1, svm_f1, cnn_f1, hyb_f1
    ],
    "AUC-ROC": [
        cox_auc, rf_auc, svm_auc, cnn_auc, hyb_auc
    ],
    "Training Time (s)": [
        cox_time, rf_time, svm_time, cnn_time, hyb_time
    ]
})

# Add FLOPs to the DataFrame (setting to NaN as 'profile' function is undefined/causing issues)
# If FLOPs calculation is required, torch.profiler or similar needs to be correctly implemented and imported.
results_df['FLOPs (M)'] = [np.nan, np.nan, np.nan, np.nan, np.nan] # Set to NaN initially

# Calculate Efficiency Score (Accuracy / Training Time (s))
results_df["Efficiency Score"] = results_df["Accuracy"] / results_df["Training Time (s)"]

# Create a figure and a primary axes object
fig, ax1 = plt.subplots(figsize=(14, 7))

# On ax1, create a bar plot for Training Time (s)
sns.barplot(
    x='Model',
    y='Training Time (s)',
    data=results_df,
    ax=ax1,
    color='skyblue',
    label='Training Time (s)'
)
ax1.set_xlabel('Model')
ax1.set_ylabel('Training Time (s)', color='skyblue')
ax1.tick_params(axis='y', labelcolor='skyblue')
ax1.set_title('Comparative Analysis: Training Time and Efficiency Score of Models')
ax1.set_xticklabels(ax1.get_xticklabels(), rotation=45, ha='right')

# Create a secondary y-axis for Efficiency Score
ax2 = ax1.twinx()
sns.lineplot(
    x='Model',
    y='Efficiency Score',
    data=results_df,
    ax=ax2,
    color='red',
    marker='o',
    linestyle='--',
    label='Efficiency Score'
)
ax2.set_ylabel('Efficiency Score (Accuracy / Time)', color='red')
ax2.tick_params(axis='y', labelcolor='red')

# Combine legends
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')

# Adjust the plot layout to prevent labels from overlapping
plt.tight_layout()
# Display the plot
plt.show()



nn_flops_df = results_df[results_df[
'Model'
].isin([
'1D CNN',
'Hybrid LNN–DNN'
])]
print(
"Filtered DataFrame for NN Models FLOPs:"
)
print(nn_flops_df)

import matplotlib.pyplot as plt
import seaborn as sns
# 1. Define a dictionary for custom
label_offsets = {"CoxPH": (10,5),"Random Forest": (10,-20),"SVM": (-15,10),"1D CNN": (-50,10),"Liquid NN–DNN": (10,-20)}
# Corrected model name to match results_df
# 2. Define a text_style dictionary
text_style =dict(fontweight='bold',fontsize=10,bbox=dict(boxstyle="round,pad=0.3", fc="yellow", ec="b", lw=0.5, alpha=0.8))
plt.figure(figsize=(10,8))
# 3. Increase figure size
# 3. Create a scatter plot with increased marker size
plt.scatter(results_df["Training Time (s)"],results_df["Accuracy"],s=150,zorder=2)
# 4. and 5. Iterate through each model and use plt.annotate
for i, row in results_df.iterrows():
  model_name = row["Model"]
  x_val = row["Training Time (s)"]
  y_val = row["Accuracy"]
  offset_x, offset_y = label_offsets.get(model_name, (10,5))
# Default offset if not specified
  plt.annotate(model_name,(x_val, y_val),xytext=(offset_x, offset_y),textcoords='offset points',arrowprops=dict(arrowstyle='->',connectionstyle='arc3,rad=0.3',color='gray',lw=0.7),ha='center',va='bottom',**text_style)
# 6. Apply the defined text_style

# 7. Set axis labels
plt.xlabel("Training Time (s)")
plt.ylabel("Accuracy")
# 8. Set the plot title
plt.title("Pareto Front: Accuracy vs Time (with adjusted labels)")
# 9. Add a grid with improved visibility
plt.grid(True, alpha=0.5, linestyle='--')
# 10. Ensure a tight layout
plt.tight_layout()
# 11. Display the plot
plt.show()

from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import time
import numpy as np
# Combine genomic and clinical features for classical models
X_combined = np.concatenate((X_genomic_selected, X_clinical), axis=1)
y_cv = df_scaled[target_col].values
# Initialize StratifiedKFold
# Setting n_splits to 5 for 5-fold cross-validation as a common practice.
# Shuffle=True ensures that the data is shuffled before splitting into folds, and random_state for reproducibility.
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = {
'CoxPH'
: {
'Accuracy'
: [],
'F1'
: [],
'AUC'
: [],
'Time'
: []},
'SVM'
: {
'Accuracy'
: [],
'F1'
: [],
'AUC'
: [],
'Time'
: []}
}

print("Starting K-Fold Cross-Validation for CoxPH and SVM...")
for fold, (train_index, test_index) in enumerate(kf.split(X_combined, y_cv)):
  print(f"\n--- Fold{fold+1}/{kf.n_splits}---")
  X_train_fold, X_test_fold = X_combined[train_index], X_combined[test_index]
  y_train_fold, y_test_fold = y_cv[train_index],y_cv[test_index]
# --- CoxPH (Logistic Regression) ---
  start_time = time.time()
  cox_cv = LogisticRegression(max_iter=1000, random_state=42)
  cox_cv.fit(X_train_fold, y_train_fold)
  cox_pred_fold = cox_cv.predict(X_test_fold)
  cox_prob_fold = cox_cv.predict_proba(X_test_fold)[:,1]
  end_time = time.time()
  cv_results['CoxPH']['Accuracy'].append(accuracy_score(y_test_fold, cox_pred_fold))
  cv_results['CoxPH']['F1'].append(f1_score(y_test_fold, cox_pred_fold))
  cv_results['CoxPH']['AUC'].append(roc_auc_score(y_test_fold, cox_prob_fold))
  cv_results['CoxPH']['Time'].append(end_time - start_time)
  print(f"CoxPH - Accuracy:{cv_results['CoxPH']['Accuracy'][-1]:.4f}, F1:{cv_results['CoxPH']['F1'][-1]:.4f}, AUC:{cv_results['CoxPH']['AUC'][-1]:.4f}, Time:{(end_time - start_time):.4f}s")
# --- SVM ---
  start_time = time.time()
  svm_cv = SVC(kernel=
'rbf'
, probability=
True
, random_state=
42
)
  svm_cv.fit(X_train_fold, y_train_fold)
  svm_pred_fold = svm_cv.predict(X_test_fold)
  svm_prob_fold = svm_cv.predict_proba(X_test_fold)[:,1]
  end_time = time.time()
  cv_results[
'SVM'
][
'Accuracy'
].append(accuracy_score(y_test_fold, svm_pred_fold
))
  cv_results[
'SVM'
][
'F1'
].append(f1_score(y_test_fold, svm_pred_fold))
  cv_results[
'SVM'
][
'AUC'
].append(roc_auc_score(y_test_fold, svm_prob_fold)
)
  cv_results[
'SVM'
][
'Time'
].append(end_time - start_time)
  print(f"SVM - Accuracy:{cv_results['SVM']['Accuracy'][-1]:.4f}, F1:{cv_results['SVM']['F1'][-1]:.4f}, AUC:{cv_results['SVM']['AUC'][-1]:.4f}, Time:{(end_time - start_time):.4f}s")
# Calculate and print average CV results
print("\n--- Average K-Fold Cross-Validation Results ---")
for model_name, metrics in cv_results.items():
  avg_accuracy = np.mean(metrics[
'Accuracy'
])
  avg_f1 = np.mean(metrics[
'F1'
])
  avg_auc = np.mean(metrics[
'AUC'
])
  avg_time = np.mean(metrics[
'Time'
])
  print(f"{model_name}: Accuracy = {avg_accuracy:.4f}, F1 = {avg_f1:.4f}, AUC = {avg_auc:.4f}, Time = {avg_time:.4f}s")
# Store average results for later comparison
cv_avg_results = {
'CoxPH'
: {
'Accuracy'
: np.mean(cv_results['CoxPH']['Accuracy']),
'F1'
: np.mean(cv_results['CoxPH']['F1']),
'AUC'
: np.mean(cv_results['CoxPH']['AUC']),
'Time'
: np.mean(cv_results['CoxPH']['Time'])},
'SVM'
: {
'Accuracy'
: np.mean(cv_results['SVM']['Accuracy']),
'F1'
: np.mean(cv_results['SVM']['F1']),
'AUC'
: np.mean(cv_results['SVM']['AUC']),
'Time'
: np.mean(cv_results['SVM']['Time'])}
}
# Display the stored cv_avg_results for current models
import pandas as pd
cv_df_classical = pd.DataFrame(cv_avg_results).T
print("\nCross-Validation Average Results (Classical Models):")
print(cv_df_classical)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import pandas as pd
import time
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

#Combine X_genomic_selected and X_clinical for splitting, but keep them separate for model input
X_genomic_all = X_genomic_selected
X_clinical_all = X_clinical
y_all = df_scaled[target_col].values
# Initialize StratifiedKFold
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# Extend cv_results for Hybrid LNN-DNN
cv_results['Hybrid LNN–DNN'] = {'Accuracy': [],'F1': [],'AUC': [],'Time': []}
genomic_input_size = X_genomic_all.shape[-1]
clinical_input_size = X_clinical_all.shape[-1]
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
EPOCHS =60
# Using the same number of epochs as the initial training
BATCH_SIZE =32
print("Starting K-Fold Cross-Validation for Hybrid LNN–DNN...")
for fold, (train_index, test_index) in enumerate(kf.split(X_genomic_all, y_all)):
  print(f"\n--- Fold{fold+1}/{kf.n_splits}---")
  # Split data for the current fold

  Xg_train_fold, Xg_test_fold = X_genomic_all[train_index], X_genomic_all[test_index]
  Xc_train_fold, Xc_test_fold = X_clinical_all[train_index], X_clinical_all[test_index]
  y_train_fold, y_test_fold = y_all[train_index], y_all[test_index]
  # Convert to tensors
  Xg_train_tensor = torch.FloatTensor(Xg_train_fold).unsqueeze(1).to(device)
  Xc_train_tensor = torch.FloatTensor(Xc_train_fold).to(device)
  y_train_tensor = torch.FloatTensor(y_train_fold).to(device)
  Xg_test_tensor = torch.FloatTensor(Xg_test_fold).unsqueeze(1).to(device)
  Xc_test_tensor = torch.FloatTensor(Xc_test_fold).to(device)
  y_test_tensor = torch.FloatTensor(y_test_fold).to(device)

  # Create DataLoaders for the current fold
  train_dataset = TensorDataset(Xg_train_tensor,
  Xc_train_tensor, y_train_tensor)
  train_loader_fold = DataLoader(train_dataset,
  batch_size=BATCH_SIZE, shuffle=True)
  test_dataset = TensorDataset(Xg_test_tensor, Xc_test_tensor, y_test_tensor)
  test_loader_fold = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)
  # Initialize model, criterion, and optimizer for the current fold
  model_fold = HybridLiquidDNN(genomic_features=genomic_input_size, clinical_features=clinical_input_size).to(device)
  criterion = nn.BCEWithLogitsLoss()
  optimizer = optim.Adam(model_fold.parameters(), lr=0.001)
  # Train the model for the current fold
  start_time_fold = time.time()
  for epoch in range (EPOCHS):
    model_fold.train()
    for xg, xc, y in train_loader_fold:
      optimizer.zero_grad()
      outputs = model_fold(xg, xc)
      loss = criterion(outputs, y)
      loss.backward()
      optimizer.step()
  end_time_fold = time.time()
  # Evaluate the model for the current fold
  model_fold.eval()
  y_true_fold, y_prob_fold = [], []
  with torch.no_grad():
    for xg, xc, y in test_loader_fold:
      xg, xc = xg.to(device), xc.to(device)
      logits = model_fold(xg, xc)
      probs = torch.sigmoid(logits)

      y_true_fold.extend(y.cpu().numpy())
      y_prob_fold.extend(probs.cpu().numpy())
  y_true_fold_arr = np.array(y_true_fold)
  y_prob_fold_arr = np.array(y_prob_fold)
  y_pred_fold_arr = (y_prob_fold_arr >=0.5).astype(int)

  cv_results['Hybrid LNN–DNN']['Accuracy'].append(accuracy_score(y_true_fold_arr,y_pred_fold_arr))
  cv_results['Hybrid LNN–DNN']['F1'].append(f1_score(y_true_fold_arr,y_pred_fold_arr))
  cv_results['Hybrid LNN–DNN']['AUC'].append(roc_auc_score(y_true_fold_arr,y_prob_fold_arr))
  cv_results['Hybrid LNN–DNN']['Time'].append(end_time_fold - start_time_fold)
  print(f"Hybrid LNN–DNN - Accuracy:{cv_results['Hybrid LNN–DNN']['Accuracy'][-1]:.4f}, F1:{cv_results['Hybrid LNN–DNN']['F1'][-1]:.4f}, AUC:{cv_results['Hybrid LNN–DNN']['AUC'][-1]:.4f}, Time:{(end_time_fold - start_time_fold):.4f}s")

print("\n--- Average K-Fold Cross-Validation Results (Hybrid LNN–DNN) ---")
avg_accuracy_hyb = np.mean(cv_results['Hybrid LNN–DNN']['Accuracy'])
avg_f1_hyb = np.mean(cv_results['Hybrid LNN–DNN']['F1'])
avg_auc_hyb = np.mean(cv_results['Hybrid LNN–DNN']['AUC'])
avg_time_hyb = np.mean(cv_results['Hybrid LNN–DNN']['Time'])
print(f"Hybrid LNN–DNN: Accuracy = {avg_accuracy_hyb:.4f}, F1 = {avg_f1_hyb:.4f}, AUC = {avg_auc_hyb:.4f}, Time = {avg_time_hyb:.4f}s")
# Update cv_avg_results with Hybrid LNN-DNN results
cv_avg_results['Hybrid LNN–DNN'] = {'Accuracy': avg_accuracy_hyb,'F1': avg_f1_hyb,'AUC': avg_auc_hyb,'Time': avg_time_hyb}
# Display the stored cv_avg_results for all models
cv_df_all = pd.DataFrame(cv_avg_results).T
print("\nCross-Validation Average Results (All Models):")
print(cv_df_all)

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import time
# Combine genomic and clinical features for classical models
X_combined = np.concatenate((X_genomic_selected, X_clinical), axis=1)
y_cv = df_scaled[target_col].values
print("--- Hyperparameter Tuning for CoxPH (Logistic Regression) ---")
# Define the parameter grid for Logistic Regression
param_grid_lr = {'C': [0.001,0.01,0.1,1,10,100]}
# Initialize StratifiedKFold
kf_grid = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
# Initialize GridSearchCV for Logistic Regression
grid_search_lr = GridSearchCV(estimator=LogisticRegression(max_iter=1000, random_state=42),param_grid=param_grid_lr,cv=kf_grid,scoring={'accuracy':'accuracy',
'f1'
:
'f1'
,
'roc_auc'
:
'roc_auc'
},
refit=
'roc_auc'
,
# Refit the estimator with the best found parameters on the whole dataset
verbose=
1
,
n_jobs=
-1
# Use all available cores
)
# Fit GridSearchCV
start_time_lr = time.time()
grid_search_lr.fit(X_combined, y_cv)
end_time_lr = time.time()
# Print best parameters and best scores
print(f"\nBest parameters for CoxPH (Logistic Regression):{grid_search_lr.best_params_}")
print(f"Best ROC_AUC score:{grid_search_lr.best_score_:.4f}")
# Get the best scores for all metrics
best_lr_index = grid_search_lr.cv_results_['rank_test_roc_auc'].argmin()
best_lr_accuracy = grid_search_lr.cv_results_['mean_test_accuracy'][best_lr_index]
best_lr_f1 = grid_search_lr.cv_results_['mean_test_f1'][best_lr_index]
print(f"Best average Accuracy:{best_lr_accuracy:.4f}")
print(f"Best average F1-score:{best_lr_f1:.4f}")
print(f"Total time for CoxPH GridSearch:{end_time_lr - start_time_lr:.2f}s")
# Store best results for later comparison
best_tuned_results = {'CoxPH': {'Accuracy': best_lr_accuracy,'F1': best_lr_f1,'AUC': grid_search_lr.best_score_,'Time': end_time_lr - start_time_lr,'Best_Params': grid_search_lr.best_params_}}



from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
# Assuming y_test, cox_prob, rf_prob, svm_prob, cnn_prob, y_prob (hybrid) are available from kernelstate
# Consolidate model probabilities
models_prob = {
"CoxPH"
: cox_prob,
"Random Forest"
: rf_prob,
"SVM"
: svm_prob,
"1D CNN"
: cnn_prob,
"Hybrid LNN–DNN"
: y_prob
# This is the y_prob from the hybrid model'sevaluation
}
plt.figure(figsize=(10,8))
for model_name, probabilities in models_prob.items():
  fpr, tpr, _ = roc_curve(y_test, probabilities)
  roc_auc = auc(fpr, tpr)
  plt.plot(fpr, tpr, lw=2, label=f'{model_name}(AUC ={roc_auc:.4f})')
plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--', label='Random (AUC = 0.50)')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curves for All Models')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

"""# Visualizing Confusion Matrix Components keyboardarrowdown (Stacked Bar Chart)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# Assuming 'cm' is available from previous execution
# cm = array([[TN, FP],
# [FN, TP]])
TN, FP, FN, TP = cm.ravel()
# Prepare data for stacked bar chart
data = {
'Actual Outcome': ['Non-Survival', 'Non-Survival', 'Survival', 'Survival'],
'Predicted Outcome': ['Non-Survival', 'Survival', 'Non-Survival', 'Survival'],
'Count': [TN, FP, FN, TP]
}
confusion_counts_df = pd.DataFrame(data)
# Pivot for stacked bar chart
plot_data = confusion_counts_df.pivot(index='Actual Outcome', columns='Predicted Outcome', values='Count')
# Plotting the stacked bar chart
fig, ax = plt.subplots(figsize=(8, 6))
plot_data.plot(kind='bar', stacked=True, ax=ax, color=['skyblue', 'lightcoral'])
ax.set_title('Confusion Matrix Breakdown: Actual vs. Predicted Outcomes')
ax.set_ylabel('Number of Instances')
ax.set_xlabel('Actual Outcome')
ax.set_xticklabels(plot_data.index, rotation=0)
ax.legend(title='Predicted Outcome', loc='upper left', bbox_to_anchor=(1, 1))
# Add count labels on the bars
for container in ax.containers:
  for patch in container.patches:
    width = patch.get_width()
    height = patch.get_height()
    x, y = patch.get_xy()
    if height > 0:
      ax.text(x + width/2, y + height/2, int(height),
              ha='center', va='center', color='black', fontweight='bold')
plt.tight_layout()
plt.show()



"""# LNN"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import time
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import pandas as pd
import ncps.torch as ncps # Import for ncps.LTC

# Define the PureLNN model class
class PureLNN(nn.Module):
    def __init__(self, genomic_features_size):
        super().__init__()
        liquid_units = 32 # Use consistent units with HybridLiquidDNN's genomic branch
        self.genomic_projection = nn.Linear(genomic_features_size, liquid_units)
        self.liquid = ncps.LTC(
            input_size=liquid_units, # LTC input size now matches its units
            units=liquid_units # Reduced units for memory footprint
        )
        self.classifier = nn.Sequential(
            nn.Linear(liquid_units, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1)
        )

    def forward(self, xg):
        # xg is expected to be [batch_size, 1, genomic_features_size]
        xg_projected = self.genomic_projection(xg.squeeze(1)).unsqueeze(1) # Project and maintain sequence dim
        liquid_out, _ = self.liquid(xg_projected)
        # liquid_out will be [batch_size, 1, liquid_units]
        g_feat = liquid_out.squeeze(1) # Remove the sequence_length dimension
        return self.classifier(g_feat).squeeze() # Squeeze to remove single-dim output if present

# Import pandas for checking type
# Ensure that Xg_train, Xg_test, y_train, y_test are available from previous steps
# and PureLNN class is defined.
# 1. Define genomic_features_size
genomic_features_size = Xg_train.shape[-1]
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 2. Initialize the PureLNN model
pure_lnn_model = PureLNN(genomic_features_size=genomic_features_size).to(device)
# 3. Define the loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(pure_lnn_model.parameters(), lr=0.001)
# Convert y_train and y_test to torch.FloatTensor explicitly if they are not already
# (They might be pandas Series from earlier notebook state)
y_train_tensor = torch.FloatTensor(y_train.values).to(device) if isinstance (y_train, pd.Series) else y_train.to(device)
y_test_tensor = torch.FloatTensor(y_test.values).to(device) if isinstance (y_test, pd.Series) else y_test.to(device)
# 4. Create DataLoader instances
# Xg_train and Xg_test are already unsqueezed as [B, 1, F] from earlier setup for HybridLNN
train_dataset_lnn = TensorDataset(Xg_train, y_train_tensor)
train_loader_lnn = DataLoader(train_dataset_lnn, batch_size=32, shuffle=True)
test_dataset_lnn = TensorDataset(Xg_test, y_test_tensor)
test_loader_lnn = DataLoader(test_dataset_lnn, batch_size=32, shuffle=False)
EPOCHS_LNN = 60
# Ensuring a sufficient number of epochs for fair comparison
print(f"Starting training for Pure LNN model on {device}...")
# 5. Implement a training loop and 6. Measure training time
start_time_lnn = time.time()
for epoch in range(EPOCHS_LNN):
    pure_lnn_model.train()
    total_loss = 0
    for xg, y in train_loader_lnn:
        # y is already on device from TensorDataset creation if y_train_tensor was moved to device
        xg, y = xg.to(device), y.to(device)
        optimizer.zero_grad()
        outputs = pure_lnn_model(xg)
        loss = criterion(outputs, y) # Ensure outputs and y have compatible shapes
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    # Print loss every few epochs (optional, but good for tracking)
    if epoch % 10 == 0:
        print(f"Epoch {epoch+1}/{EPOCHS_LNN}|Loss:{total_loss / len(train_loader_lnn):.4f}")

end_time_lnn = time.time()
pure_lnn_training_time = end_time_lnn - start_time_lnn
print(f"Pure LNN training finished in {pure_lnn_training_time:.2f} seconds.")


# 7. Evaluate the Pure LNN model
pure_lnn_model.eval()
y_true_lnn, y_prob_lnn = [], []
with torch.no_grad():
  for xg, y in test_loader_lnn:
    xg, y = xg.to(device), y.to(device)
    logits = pure_lnn_model(xg)
    probs = torch.sigmoid(logits)
    y_true_lnn.extend(y.cpu().numpy())
    y_prob_lnn.extend(probs.cpu().numpy())

y_true_lnn_arr = np.array(y_true_lnn)
y_prob_lnn_arr = np.array(y_prob_lnn)
y_pred_lnn_arr = (y_prob_lnn_arr >= 0.5).astype(int)

lnn_acc = accuracy_score(y_true_lnn_arr, y_pred_lnn_arr)
lnn_f1 = f1_score(y_true_lnn_arr, y_pred_lnn_arr)
lnn_auc = roc_auc_score(y_true_lnn_arr, y_prob_lnn_arr)
lnn_time = pure_lnn_training_time # Use measured time

print(f"\nPure LNN Model Evaluation:")
print(f"Accuracy: {lnn_acc:.4f}")
print(f"F1-Score: {lnn_f1:.4f}")
print(f"AUC-ROC: {lnn_auc:.4f}")
print(f"Training Time: {lnn_time:.4f}s")

# 11. Store all calculated metrics
pure_lnn_metrics = {
    'Accuracy': lnn_acc,
    'F1-Score': lnn_f1,
    'AUC-ROC': lnn_auc,
    'Training Time (s)': lnn_time
}
print("\nPure LNN Metrics:")
print(pure_lnn_metrics)

# 1. Define genomic_features_size
genomic_features_size = Xg_train.shape[-1]
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 2. Initialize the PureLNN model
pure_lnn_model = PureLNN(genomic_features_size=genomic_features_size).to(device)
# 3. Define the loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(pure_lnn_model.parameters(), lr=0.001)
# Convert y_train and y_test to torch.FloatTensor explicitly if they are not already
# (They might be pandas Series from earlier notebook state)
y_train_tensor = torch.FloatTensor(y_train.values).to(device) if isinstance(y_train, pd.Series) else y_train.to(device)
y_test_tensor = torch.FloatTensor(y_test.values).to(device) if isinstance(y_test, pd.Series) else y_test.to(device)
# 4. Create DataLoader instances
# Xg_train and Xg_test are already unsqueezed as [B, 1, F] from earlier setup for HybridLNN
train_dataset_lnn = TensorDataset(Xg_train, y_train_tensor)
train_loader_lnn = DataLoader(train_dataset_lnn, batch_size=32, shuffle=True)
test_dataset_lnn = TensorDataset(Xg_test, y_test_tensor)
test_loader_lnn = DataLoader(test_dataset_lnn, batch_size=32, shuffle=False)
EPOCHS_LNN = 60
# Ensuring a sufficient number of epochs for fair comparison
print(f"Starting training for Pure LNN model on {device}...")
pure_lnn_loss_history = []
# List to store training loss per epoch
pure_lnn_test_loss_history = []
# List to store test loss per epoch
# 5. Implement a training loop and 6. Measure training time
start_time_lnn = time.time()
for epoch in range(EPOCHS_LNN):
  pure_lnn_model.train()
  total_train_loss = 0
  for xg, y in train_loader_lnn:
    # y is already on device from TensorDataset creation if y_train_tensor was moved to device
    xg, y = xg.to(device), y.to(device)
    optimizer.zero_grad()
    outputs = pure_lnn_model(xg)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()
    total_train_loss += loss.item()
  avg_train_loss = total_train_loss / len(train_loader_lnn)
  pure_lnn_loss_history.append(avg_train_loss)
# Store average training loss for the epoch
# --- Evaluate on test set ---
  pure_lnn_model.eval()
  total_test_loss = 0
  with torch.no_grad():
    for xg, y in test_loader_lnn:
      xg, y = xg.to(device), y.to(device)
      outputs = pure_lnn_model(xg)
      loss = criterion(outputs, y)
      total_test_loss += loss.item()
  avg_test_loss = total_test_loss / len(test_loader_lnn)
  pure_lnn_test_loss_history.append(avg_test_loss)
# Store average test loss for the epoch
  pure_lnn_model.train()
# Set model back to training mode
  if epoch % 10 == 0:
    print(f"Epoch{epoch+1}/{EPOCHS_LNN}|Train Loss:{avg_train_loss:.4f}|Test Loss:{avg_test_loss:.4f}")

end_time_lnn = time.time()
pure_lnn_training_time = end_time_lnn - start_time_lnn
print(f"Pure LNN training finished in {pure_lnn_training_time:.2f} seconds.")
# 7. After training, set the model to evaluation mode
pure_lnn_model.eval()
# 8. Iterate through the test DataLoader to make predictions and collect true labels and predicted probabilities
y_true_lnn, y_prob_lnn = [], []
with torch.no_grad():
  for xg, y in test_loader_lnn:

# y is already on device from TensorDataset creation if y_test_tensor was moved to device
    xg, y = xg.to(device), y.to(device)
    logits = pure_lnn_model(xg)
    probs = torch.sigmoid(logits)
    y_true_lnn.extend(y.cpu().numpy())
    y_prob_lnn.extend(probs.cpu().numpy())
# 9. Convert collected true labels and probabilities to NumPy arrays
y_true_lnn_arr = np.array(y_true_lnn)
y_prob_lnn_arr = np.array(y_prob_lnn)
y_pred_lnn_arr = (y_prob_lnn_arr >= 0.5).astype(int)
# 10. Calculate Accuracy, F1-Score, and AUC-ROC
pure_lnn_accuracy = accuracy_score(y_true_lnn_arr, y_pred_lnn_arr)
pure_lnn_f1 = f1_score(y_true_lnn_arr, y_pred_lnn_arr)
pure_lnn_auc = roc_auc_score(y_true_lnn_arr, y_prob_lnn_arr)
print(f"\nPure LNN Model Evaluation:")
print(f"Accuracy: {pure_lnn_accuracy:.4f}")
print(f"F1-Score: {pure_lnn_f1:.4f}")
print(f"AUC-ROC: {pure_lnn_auc:.4f}")
print(f"Training Time: {pure_lnn_training_time:.4f}s")
# 11. Store all calculated metrics
pure_lnn_metrics = {
'Accuracy': pure_lnn_accuracy,
'F1-Score': pure_lnn_f1,
'AUC-ROC': pure_lnn_auc,
'Training Time (s)': pure_lnn_training_time
}
print("\nPure LNN Metrics:")
print(pure_lnn_metrics)

"""# DNN

"""

import torch.nn as nn

class PureDNN (nn.Module):
  def __init__(self,clinical_features_size):
    super().__init__()
    self.network = nn.Sequential(nn.Linear(clinical_features_size,64),nn.ReLU(),nn.Dropout(0.3),nn.Linear(64,32),nn.ReLU(),nn.Dropout(0.3),nn.Linear(32,1))
# Output layer for binary classification

  def forward(self,xc):
    return self.network(xc).squeeze()
# Squeeze to [batch_size] for BCEWithLogitsLoss

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import time
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
# Ensure that Xc_train, Xc_test, y_train_tensor, y_test_tensor are available from previous steps
# and PureDNN class is defined.
# 1. Define clinical_features_size
clinical_features_size = Xc_train.shape[-1]
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 2. Initialize the PureDNN model
pure_dnn_model = PureDNN(clinical_features_size=clinical_features_size).to(device)
# 3. Define the loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(pure_dnn_model.parameters(), lr=0.001)
# 4. Create DataLoader instances
# Make sure y_train and y_test are properly converted for DNN
Xc_train_dnn_tensor = torch.FloatTensor(Xc_train).to(device)
y_train_dnn_tensor = torch.FloatTensor(y_train.values).to(device) # Using y_train pandas Series

Xc_test_dnn_tensor = torch.FloatTensor(Xc_test).to(device)
y_test_dnn_tensor = torch.FloatTensor(y_test.values).to(device) # Using y_test pandas Series

# --- DEBUGGING PRINTS ---
print(f"DEBUG: Shape of Xc_test: {Xc_test.shape}")
print(f"DEBUG: Shape of y_test.values: {y_test.values.shape}")
print(f"DEBUG: Shape of Xc_test_dnn_tensor: {Xc_test_dnn_tensor.shape}")
print(f"DEBUG: Shape of y_test_dnn_tensor: {y_test_dnn_tensor.shape}")
# --- END DEBUGGING PRINTS ---

train_dataset_dnn = TensorDataset(Xc_train_dnn_tensor, y_train_dnn_tensor)
train_loader_dnn = DataLoader(train_dataset_dnn, batch_size=32, shuffle=True)
test_dataset_dnn = TensorDataset(Xc_test_dnn_tensor, y_test_dnn_tensor)
test_loader_dnn = DataLoader(test_dataset_dnn, batch_size=32, shuffle=False)
EPOCHS_DNN = 60
# Ensuring a sufficient number of epochs for fair comparison
print(f"Starting training for Pure DNN model on {device}...")
pure_dnn_loss_history = []
# List to store training loss per epoch

pure_dnn_test_loss_history = []
# List to store test loss per epoch
# 5. Implement a training loop and 6. Measure training time
start_time_dnn = time.time()
for epoch in range(EPOCHS_DNN):
  pure_dnn_model.train()
  total_train_loss = 0
  for xc, y in train_loader_dnn:
    xc, y = xc.to(device), y.to(device)
    optimizer.zero_grad()
    outputs = pure_dnn_model(xc)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()
    total_train_loss += loss.item()

  avg_train_loss = total_train_loss / len(train_loader_dnn)
  pure_dnn_loss_history.append(avg_train_loss)

  # Store average training loss for the epoch
  # --- Evaluate on test set ---
  pure_dnn_model.eval()
  total_test_loss = 0
  with torch.no_grad():
    for xc, y in test_loader_dnn:
      xc, y = xc.to(device), y.to(device)
      outputs = pure_dnn_model(xc)
      loss = criterion(outputs, y)
      total_test_loss += loss.item()
  avg_test_loss = total_test_loss / len(test_loader_dnn)
  pure_dnn_test_loss_history.append(avg_test_loss)

  # Store average test loss for the epoch

  pure_dnn_model.train()

  # Set model back to training mode
  if epoch % 10 == 0:
    print(f"Epoch{epoch+1}/{EPOCHS_DNN}|Train Loss:{avg_train_loss:.4f}|Test Loss:{avg_test_loss:.4f}")

end_time_dnn = time.time()
pure_dnn_training_time = end_time_dnn - start_time_dnn
print(f"Pure DNN training finished in {pure_dnn_training_time:.2f} seconds.")

# 7. After training, set the model to evaluation mode
pure_dnn_model.eval()
# 8. Iterate through the test DataLoader to make predictions and collect true labels and predicted probabilities
y_true_dnn, y_prob_dnn = [], []
with torch.no_grad():
  for xc, y in test_loader_dnn:
    xc, y = xc.to(device), y.to(device)
    logits = pure_dnn_model(xc)
    probs = torch.sigmoid(logits)
    y_true_dnn.extend(y.cpu().numpy())
    y_prob_dnn.extend(probs.cpu().numpy())
# 9. Convert collected true labels and probabilities to NumPy arrays
y_true_dnn_arr = np.array(y_true_dnn)
y_prob_dnn_arr = np.array(y_prob_dnn)
y_pred_dnn_arr = (y_prob_dnn_arr >= 0.5).astype(int)
# 10. Calculate Accuracy, F1-Score, and AUC-ROC
pure_dnn_accuracy = accuracy_score(y_true_dnn_arr, y_pred_dnn_arr)
pure_dnn_f1 = f1_score(y_true_dnn_arr, y_pred_dnn_arr)
pure_dnn_auc = roc_auc_score(y_true_dnn_arr, y_prob_dnn_arr)
print(f"\nPure DNN Model Evaluation:")
print(f"Accuracy: {pure_dnn_accuracy:.4f}")
print(f"F1-Score: {pure_dnn_f1:.4f}")
print(f"AUC-ROC: {pure_dnn_auc:.4f}")
print(f"Training Time: {pure_dnn_training_time:.4f}s")
# 11. Store all calculated metrics
pure_dnn_metrics = {
'Accuracy': pure_dnn_accuracy,
'F1-Score': pure_dnn_f1,
'AUC-ROC': pure_dnn_auc,
'Training Time (s)': pure_dnn_training_time
}
print("\nPure DNN Metrics:")
print(pure_dnn_metrics)

import pandas as pd
import numpy as np
# Initialize final_comparison_df from results_df
final_comparison_df = results_df.copy()

# Prepare pure_lnn_metrics and pure_dnn_metrics to match the columns of final_comparison_df
# This ensures that when they are converted to DataFrames, they have the same number of columns

# For Pure LNN
pure_lnn_data = pure_lnn_metrics.copy()
pure_lnn_data['FLOPs (M)'] = np.nan  # Add missing column with NaN
pure_lnn_data['Efficiency Score'] = pure_lnn_data['Accuracy'] / pure_lnn_data['Training Time (s)'] # Calculate efficiency score
pure_lnn_df = pd.DataFrame([pure_lnn_data], index=['Pure LNN'])

# For Pure DNN
pure_dnn_data = pure_dnn_metrics.copy()
pure_dnn_data['FLOPs (M)'] = np.nan  # Add missing column with NaN
pure_dnn_data['Efficiency Score'] = pure_dnn_data['Accuracy'] / pure_dnn_data['Training Time (s)'] # Calculate efficiency score
pure_dnn_df = pd.DataFrame([pure_dnn_data], index=['Pure DNN'])

# Reset index of final_comparison_df to concatenate easily
final_comparison_df_reset = final_comparison_df.set_index('Model')

# Concatenate the new models' dataframes with the existing final_comparison_df
updated_final_comparison_df = pd.concat([final_comparison_df_reset, pure_lnn_df, pure_dnn_df])

# Reset index and rename 'Model' column if needed
updated_final_comparison_df = updated_final_comparison_df.reset_index().rename(columns={'index': 'Model'})
print("\n--- Updated Final Consolidated Model Comparison Table ---")
display(updated_final_comparison_df)
# Overwrite the old final_comparison_df for subsequent use
final_comparison_df = updated_final_comparison_df

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# Data provided by the user
data = {
'Model': ['CoxPH', 'Random Forest', 'SVM', '1D CNN', 'Hybrid LNN–DNN', 'Pure LNN', 'Pure DNN'],
'Accuracy': [0.999475, 0.997373, 0.999475, 0.784777, 0.999475, 1.000000, 0.661417],
'F1-Score': [0.999377, 0.996869, 0.999377, 0.705036, 0.999377, 1.000000, 0.582524],
'AUC-ROC': [0.999740, 0.999627, 0.999683, 0.882749, 0.999839, 1.000000, 0.715979],
'Training Time (s)': [0.508453, 11.190110, 6.591529, 1.154282, 25.570447, 26.640296, 8.756549]
}
df_results = pd.DataFrame(data)
print("DataFrame created from user-provided data:")
display(df_results)

# Grouped bar chart for Accuracy, F1-Score, and AUC-ROC
metrics_to_plot = [
"Accuracy"
,
"F1-Score"
,
"AUC-ROC"
]
x = np.arange(len(df_results))
width =0.25
# width of each bar
plt.figure(figsize=(14,7))
for i, metric in enumerate (metrics_to_plot):
  plt.bar(x + i*width, df_results[metric], width, label=metric)
  plt.xticks(x + width, df_results["Model"], rotation=45, ha='right')
  plt.ylabel("Score")
  plt.title("Comparative Performance Metrics of Models")
  plt.legend()
  plt.grid(axis='y', alpha=0.3)
  plt.tight_layout()
  plt.show()

"""# Training Time Comparison"""

# Bar chart for Training Time (s)
plt.figure(figsize=(12,6))
sns.barplot(x='Model', y='Training Time (s)', data=df_results, palette='magma')
plt.xlabel('Model')
plt.ylabel('Training Time (s)')
plt.title('Comparative Training Time of Models')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

